[watch]
ignore = ["./public"]

[serve]
address = "127.0.0.1"
port = 4001
open = false
no_autoreload = false

[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = ["check", "--target", "wasm32-unknown-unknown"]
