[package]
name = "leptos-tiptap"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.3", default-features = false, features = [
    "csr",
    "tracing",
    "stable",
] }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.5"
tracing = "0.1"
urlencoding = "2"
wasm-bindgen = "0.2"
